name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run make
      run: make
      
    - name: install valgrind
      run: apt update && apt install valgrind -y

    - name: Run test
      run: make test
      
    - name: clean
      run: make fclean
