name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install valgrind
      run: sudo apt update && sudo apt install valgrind -y
    
    - name: Run make
      run: make

    - name: Run test
      run: make test

    - name: Run test valgrind
      run: make testv
    
    - name: Run test0
      run: make test0
    
    - name: Run test1
      run: make test1

    - name: Run test2
      run: make test2

    - name: clean
      run: make fclean
